In [1]:
import numpy as np
import matplotlib.pyplot as plt
from KMCLib import *
import time
#from KMCAnalysis_single_trajectory import *

# -----------------------------------------------------------------------------
# KMCLib version 2.0-a1
# Distributed under the GPLv3 license
# Copyright (C)  2012-2016  Mikael Leetmaa
# Developed by Mikael Leetmaa <leetmaa@kth.se>
#
# This program is distributed in the hope that it will be useful
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# LICENSE and README files, and the source code, for details.
#
# You should have received a copy of the GNU General Public License version 3
# (GPLv3) along with this program. If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------



In [2]:
# parameters :
size = 10
# Define a squared unit cell of size 1x1x1.
cell_vectors = [[   1.000000e+00,   0.000000e+00,   0.000000e+00],
                [   0.000000e+00,   1.000000e+00,   0.000000e+00],
                [   0.000000e+00,   0.000000e+00,   1.000000e+00]]
# Define a unique point within the unit cell
basis_points = [[   0.500000e+00,   0.500000e+00,   0.500000e+00]]
unit_cell = KMCUnitCell(cell_vectors=cell_vectors,
                        basis_points=basis_points)
                        # Define a 1D lattice of size size
lattice = KMCLattice(unit_cell=unit_cell,
                     repetitions=(size,size,1),
                     periodic=(False, False, False))


In [3]:
types = ['S']*(size**2)
types[size**2//2+size//2] = 'A'
Nparticle = size
config = KMCConfiguration(lattice=lattice,
                          types=types,
                          possible_types=['S','A','B','C'])

In [7]:
from KMCLib.PluginInterfaces.KMCRateCalculatorPlugin import KMCRateCalculatorPlugin
Jaa,Jbb,Jcc = -10.,-10.,0.
Jab,Jac,Jbc = 1.,0.,0.

Vs = {'AA':Jaa,
        'BB':Jbb,
        'CC':Jcc,
        'AB':Jab,
        'BA':Jab,
        'AC':Jac,
        'CA':Jac,
        'BC':Jbc,
        'CB':Jbc,
        'AS':0.,
        'SA':0.,
        'BS':0.,
        'SB':0.,
        'CS':0.,
        'SC':0.,
        'SS':0.}

class CustomPlugin(KMCRateCalculatorPlugin):
    def rate(self,coords,types_before,types_after,rate_constant,process_number,global_coordinate):
        #print()
        print(types_before)
        print(types_after)
        print(coords)
        print([global_coordinate[0]+coords[i][0] for i in range(types_before.__len__())])
        print(process_number)
        #print()
        neigh_B4 = {i:j for i,j in zip(coords[:,0],types_before)}
        neigh_AF = {i:j for i,j in zip(coords[:,0],types_after)}
        #Eb4,Eaf = 0.,0.        
        #if process_number<=11:
            # diffusive move
        #else:
            # chemical move
        return 1.#rate_constant*np.exp((-Eaf+Eb4)/2)

    
    def cutoff(self):
        """ Determines the cutoff for this custom model """
        return None

In [8]:
import TwoDProcesses as Process
# just diffusive process so far
interactions  = Process.make_interactions(1.,1.,ChemicalMove=True)
#from CustomRate import *
interactions.setRateCalculator(rate_calculator=CustomPlugin)

# Generate the KMC model to run.
model = KMCLatticeModel(configuration=config,
                        interactions=interactions)
control_parameters = KMCControlParameters(number_of_steps=2,
                                          dump_interval=1,
                                          analysis_interval=1,
                                          seed=None)

In [9]:
t0 = time.perf_counter()
model.run(control_parameters,trajectory_filename='test.py',
          trajectory_type='xyz')#,
          #analysis = MyAnalysis)
print('execution time : '+str(time.perf_counter()-t0))

 KMCLib: setting up the backend C++ object.
('A', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S')
('S', 'A', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S')
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [-1. -1.  0.]
 [-1.  1.  0.]
 [ 1. -1.  0.]
 [ 1.  1.  0.]
 [-2.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  2.  0.]
 [ 2.  0.  0.]]
[5.5, 4.5, 5.5, 5.5, 6.5, 4.5, 4.5, 6.5, 6.5, 3.5, 5.5, 5.5, 7.5]
0
('S', 'A', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S')
('A', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S')
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [-1. -1.  0.]
 [-1.  1.  0.]
 [ 1. -1.  0.]
 [ 1.  1.  0.]
 [-2.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  2.  0.]
 [ 2.  0.  0.]]
[6.5, 5.5, 6.5, 6.5, 7.5, 5.5, 5.5, 7.5, 7.5, 4.5, 6.5, 6.5, 8.5]
1
 KMCLib: Runing for 2 steps, starting from time: 0.000000

('A', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S')
('S', 'A', 'S', 'S', 'S', 'S', 'S', 'S'